### PR TITLE
Work

### LINKED ISSUE #10: SignUpActivity update

### PR DESCRIPTION
**Pull request by DhruvWalia03**
Fixes #10

### CODE REVIEW

**Comment by yash1ts** [comment]
Resolve the merge conflicts.

**Comment by DhruvWalia03** [comment]
sir joh do files me change kiya hai wohi conflict kr rhi hai

**Comment by yash1ts** [comment]
Use Github desktop to see which files are conflicting. I f you can't do that I will have to commit to this pull request.

**Comment by DhruvWalia03** [comment]
> Use Github desktop to see which files are conflicting. If you can't do that I will have to commit to this pull request.
sir, I have made changes in sigupactivity and strings.xml file and those two files are conflicting

**Comment by yash1ts** [comment]
> > Use Github desktop to see which files are conflicting. If you can't do that I will have to commit to this pull request.
> > sir, I have made changes in sigupactivity and strings.xml file and those two files are conflicting

So you need to resolve the conflict. Conflict arises because two contributors have made changes in same file. you need to pull changes from repo. Then you will see pull failed because of conflict then edit file such that their and your both changes are saved. I think this is the way it should be but I post commit if this is problem is not solved this way.

**Comment by yash1ts** [comment]
This issue is already solved. Please look at the commits.

**Pull request closed without merging**
